# Main config

# Basic info
site_name: aschegolkov
site_description: selfdocs
site_author: aschegolkov
repo_name: aschegolkov/knowledge_base
repo_url: https://github.com/aschegolkov/knowledge_base

# Параметры для документов
docs_dir: docs

# Extensions to MD
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji

# Social network links

# MKDocs theme params
theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: img/icon.png
  favicon: img/icon.png

#extra_css:
#  - stylesheets/extra.css

# Used plugins
plugins:
  - search
  - autorefs
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - awesome-pages:
      collapse_single_pages: true
      strict: false


# Copyright
copyright: "aschegolkov 2024"
